= Introduction

ClarisWorks / AppleWorks documents are a closed file format. This page is an
attempt to describe this format(s) for the purpose of importing documents into
newer more open formats for archiving.

After being frustrated that I wasn't able to normalize old files with Xena I
set out figure out how to read this file to develop a plugin. I was sure that
someone had already written a plugin for OpenOffice or KOffice or something.
This page is a collection of all of the resources and info I have been able
to find, as well as my own discoveries about this file format. I plan on
continuing work until I have enough knowledge to develop a reader that can at
least extract text and some basic formatting of simple documents. From what I
can tell, I think this first goal can be met. If anyone else out there can
find anything else on their own, please update this wiki or email me your thoughts.
Code and test files can be found at: https://github.com/teacurran/appleworks-parser

== Supported Versions

* ClarisWorks 4.x (partial)
* ClarisWorks 5.x (Windows and Mac OS 9)
* AppleWorks 6.x (Mac OS X)

== Current Capabilities

* ✅ Document version detection
* ✅ Document type detection (Word Processing, Drawing, Painting, Spreadsheet)
* ✅ Page dimensions and margins
* ✅ Text content extraction
* ✅ Font list extraction (FNTM block)
* ✅ Block index parsing (ETBL table of contents)
* ✅ Conversion to ODF format
* ⚠️ Style runs (partial - structure identified but not fully parsed)
* ❌ Embedded images
* ❌ Spreadsheet cell data
* ❌ Drawing/painting graphics

== Priorities

* ✅ Discover how to determine the start of the content block
* ✅ Figure out the format of DSET
* ⚠️ Discover how to read the style attributes to apply to the content (in progress)
* ❌ Develop plugin for Xena
* ❌ Develop plugin for general use

== Example Files

Example files I am using can be found in the `test_files` directory.

Please email me any examples you might have, especially if you have a version of
ClarisWorks older than 5.0.

== Document Format

The following sections describe the binary format of ClarisWorks/AppleWorks files.

include::header.adoc[]

include::document_types.adoc[]

include::keywords.adoc[]

include::markers.adoc[]

include::etbl.adoc[]

include::fonts.adoc[]

include::style_runs.adoc[]

=== Document Info

There is a summary stored after the main header but before the first DSET.

.Document Info
[width="80%",grid="all", valign="top", options="header"]
|=========================================================
|desc |length (bytes) |notes
|full length + 1 | 4 |
|abbreviated length| 1 |
|=========================================================

* This is used to store an abbreviated table of properties for:
** Title
** Author
** Version
** Keywords
** Category
** Description

*Each field is allowed 255 bytes of content +
*Full content is always available in the DSUM section

=== Document Content

Content appears to start right after the end of the first DSET block.

Strings in the document start with the first 4 bytes indicating the length of the string.

The content area will have several strings in a row without any termination.

The last string appears to be null terminated.

Footnotes show up in the text as 0x02.

Character encoding is MacRoman.

=== Document TOC (ETBL)

The ETBL block at the end of the file contains a table of contents with offsets to all major blocks.
See link:etbl.adoc[ETBL documentation] for detailed structure.

== File Validation

=== BOBO Signature

All valid ClarisWorks/AppleWorks files contain the ASCII string "BOBO" at offset 4-7.

=== File End Marker

In all versions tested, documents end with:
----
FF FE FD FC FB FA F9 F8 F0 F1 F2 F3 F4 F5 F6 F7
----

This 16-byte marker always follows the ETBL block and can be used to verify file integrity.

== Misc

=== Passwords
* Password protected documents do not have their content protected.
* Password is not stored in the file.
* It probably stores a checksum because there isn't much difference with password length.

== Other Efforts

=== ABIWord
ClarisWorks import for ABIWord (non-functional but has some info)
http://svn.abisource.com/abiword/trunk/plugins/clarisworks/xp/

=== OpenOffice / StarOffice
If you do a ton of google searches, you find a lot of pages that say that
StarOffice could open ClarisWorks documents. This was done with the W4W filter.
After a lot of digging, I believe that these filters live in OpenOffice in the
Framework project. After checking out the source for the Framework project, I
believe that the ClarisWorks import support was non-existent. If I am reading
the source correctly, it looks like this filter simply opens the document as
ASCII. If this is the case, I don't know why they even bothered to say they
had a filter. If this is not the case someone please correct me.

=== Proprietary
* Old versions of DataViz can convert documents. Product appears dead but
still for sale.
* MacText can convert older .cwk files to rtf, word2, and Word Perfect.
* XTND - there is a lot of info out there about XTND filters as part of
system 6 and 7. I would like to investigate if copies of these filters
could help this effort but I haven't been able to find enough info yet.

== Misc
Forum message from someone looking into the format (from 2001):
http://www.justlinux.com/forum/showthread.php?p=228151
