= Introduction

Clarisworks / Appleworks documents are a closed file format. This page is an
attempt to describe this format(s) for the purpose of importing documents into
newer more open formats for archiving.

After being frustrated that I wasn't able to normalize old files with Xena I
set out figure out how to read this file to develop a plugin. I was sure that
someone had already written a plugin for OpenOffice or KOffice or something.
This page is a collection of all of the resources and info I have been able
to find, as well as my own discoveries about this file format. I plan on
continuing work until I have enough knowledge to develop a reader that can at
least extract text and some basic formatting of simple documents. From what I
can tell, I think this first goal can be met. If anyone else out there can
find anything else on their own, please update this wiki or email me your thoughts.
code and test files can be found at: https://github.com/teacurran/appleworks-parser

== Priorities

* discover how to determine the start of the content block
* Figure out the format of DSET
* discover how to read the style attributes to apply to the content
* develop plugin for Xena
* develop plugin for general use

== Example Files

example files I am using can be found in test_files directory

Please email me any examples you might have, especially if you have a version of
ClarisWorks older than 5.0.

== Document Format
include::keywords.adoc[]

include::markers.adoc[]

include::header.adoc[]

=== Document Info
*there is a summary stored after the main header but before the first DSET

.Document Info
[width="80%",grid="all", valign="top", options="header"]
|=========================================================
|desc |length (bytes) |notes
|full length + 1 | 4 |
|abbreviated length| 1 |
|=========================================================

* This is used to store an abbreviated table of properties for:
** Title
** Author
** Version
** Keywords
** Category
** Description

*each field is allowed 255 bytes of content +
*full content is always available in the [[Projects:Archiving:AppleWorks:DSUM|DSUM]] section

=== Document Content
Content Appears to start right after the end of the first DSET block

Strings in the document start with the first 4 bytes indicating the length of the string

The content area will have several strings in a row without any termination

The last string appears to be null terminated.

footnotes show up in the text as 0x02

=== Document TOC
The TOC can contain any number of markers in any order. The data area always starts and ends with ETBL.

.Document TOC - at end of file
[width="80%",grid="all", valign="top", options="header"]
|=========================================================
|position start |length (bytes)| description |example |ascii |comments
|start position determined by other ETBL |4 |tag |4554424C |ETBL |Value indicates the total length of data in ETBL
|anywhere |4 |data | |oBIN |oBIN block offset from start of doc
|anywhere |4 |tag |4453554D |DSUM |DSUM block offset
|anywhere |4 |data | |STYL |STYL block offset
|anywhere |4 |data || BBAR |
|anywhere |4 |data || MARK| MARK block offset
|anywhere |4 |data || MRKS |
|EOF - 24 |4 |tag |4554424C |ETBL |Following Value indicates start position
|=========================================================
